routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reset_password/{token}', ['as' => 'password.reset', function($token)
{
    // implement your reset password route here!
}]);

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::post('/login', 'Auth\LoginController@postLogin');

Route::group(['prefix' => 'admin','middleware' => ['admin']], function () {
Route::get('/home', 'HomeController@index');
Route::get('/logout', 'HomeController@getSignOut');
Route::get('/getMilestones', 'HomeController@getMilestones');
Route::resource('/department', 'Admin\DepartmentController');
Route::resource('/grade', 'Admin\GradeController');
Route::resource('/designation', 'Admin\DesignationController');
Route::resource('/kpi', 'Admin\KpiController');
Route::resource('/kpiuser', 'Admin\KpiUserController');
Route::resource('/announce', 'Admin\AnnouncementController');
Route::resource('/users', 'Admin\UsersController');
Route::resource('/userlink', 'Admin\UserLinkController');
Route::resource('/milestone', 'Admin\MilestoneController');
Route::post('/copy_kpi_milestone', 'Admin\MilestoneController@copy_kpi_milestone');
Route::resource('/request_meeting', 'Admin\RequestMeetingController');
Route::resource('/notes', 'Admin\NotesController');
Route::get('/milestone/kpibyuser/{id}', 'Admin\MilestoneController@kpibyuser');
});



Route::group(['prefix' => 'user','middleware' => ['user']], function () {
Route::get('/home', 'User\HomeController@index');
Route::get('/my_overall', 'User\MyOverallController@index');
Route::get('/logout', 'User\HomeController@getSignOut');
Route::get('/getMilestones', 'User\HomeController@getMilestones');

Route::get('/kpi/create/{id}', 'User\KpiUsersController@kpiCreate');
Route::post('/kpi/store/', 'User\KpiUsersController@kpiStore');
Route::get('/milestone/create', 'User\KpiUsersController@milestoneCreate');
Route::get('/milestone/kpibyuser/{id}', 'User\KpiUsersController@kpibyuser');
Route::post('/milestone/store', 'User\KpiUsersController@milestoneStore');
Route::get('/meeting-request/{id}', 'User\MeetingRequestingController@index');//Ajax call
Route::get('/meeting-request/show/{id}', 'User\MeetingRequestingController@showAll');
Route::post('/meeting-request/state/{id}', 'User\MeetingRequestingController@updateRequest');
Route::get('/milestone/{id}', 'User\KpiUsersController@showMilestone');

Route::get('/milestone/edit/{id}', 'User\KpiUsersController@editMilestone');
Route::get('/milestone/copy/{id}', 'User\KpiUsersController@copyMilestone');
Route::post('/milestone/update/{id}', 'User\KpiUsersController@milestoneUpdate');
Route::post('/milestone/copyupdate', 'User\KpiUsersController@milestoneCopyUpdate');
Route::post('/milestone/stateupdate/{mid}/{kid}', 'User\KpiUsersController@stateupdate');

Route::get('/super_user/{id}', 'User\KpiUsersController@showSuperusers');
Route::get('/sub_users/{id}', 'User\KpiUsersController@index');
Route::get('/user_kpis/{id}', 'User\KpiUsersController@userKpiList');
Route::get('/admin_kpis/{id}', 'User\KpiUsersController@adminKpiList');
Route::post('/kpi/delete/{id}', 'User\KpiUsersController@deleteKpi');
Route::get('/milestone/delete/{id}', 'User\KpiUsersController@deleteMilestone');
Route::get('/announcement/{id}', 'User\AnnouncementController@index');
});

///Crons
Route::get('/m_deadline_inform', 'CronController@m_deadline_inform');

app/Designation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Designation extends Model
{
    protected $table = 'designations';
    protected $fillable = array('name', 'description');

    public function designation(){
        return $this->hasMany('App\User', 'designation_id', 'id');
    }

}

app/Http/Controllers/Admin/DesignationController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Designation;
use App\Http\Requests\DesignationCreateRequest;
use App\Http\Requests\DesignationUpdateRequest;

class DesignationController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('admin');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $designationInfo = Designation::all();
        return view('pages.admin.designation.index', compact('designationInfo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.designation.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DesignationCreateRequest $request)
    {
        if (Designation::create($request->only('name', 'description'))) {
            return redirect()->route('designation.create')
                ->with('success', 'Designation create successfully');
        }else{
            return redirect()->route('designation.create')
                ->with('error', 'Designation create fail');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $designationInfo = Designation::where('id', '=', $id)->first();
        return view('pages.admin.designation.edit', compact('designationInfo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DesignationUpdateRequest $request, $id)
    {
        $designationUpdate = Designation::where('id', '=', $id)->first();
      if ($designationUpdate->update($request->all())) {
            return redirect()->route('designation.index')
            ->with('success', 'Designation Update successfully');
      }else{
            return redirect()->route('designation.index')
            ->with('error', 'Designation Update fail');
      }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $designationDelete = Designation::where('id', '=', $id)->first();
        if($designationDelete->delete()){
            return redirect()->route('designation.index')
            ->with('success', 'Designation Delete Successfully');
        }else{
            return redirect()->route('designation.index')
            ->with('error', 'Designation Delete Unsuccessful');
        }
    }
}

resources/views/pages/admin/designation/create.blade.php
@extends('layouts.app')

@section('main-content')
{{-- Error message handle --}}
@if ($message = Session::get('success'))
<div class="container col-md-8">
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
@if ($message = Session::get('error'))
<div class="container">
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
{{-- Validation errors handle --}}
{{-- @if ($errors->first())
<div class="row">
	<div class="container col-md-6 col-sm-6">
		<div class="alert alert-danger" role="alert">
			<p>{{ $errors->first() }}</p>
		</div>
	</div>
</div>
@endif --}}
{{-- End: Error message handle--}}
<div class="container-fluid">
<div class="col-md-1"></div>

	<div class="col-md-10">
		
		<div class="box box-info">
			<div class="box-header with-border">
				{{-- <h3 class="box-title">Create Designation</h3> --}}
				<h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                            CREATE DESIGNATION
                        </h4>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<form action="{{ route('designation.store') }}" method="POST" role="form" enctype="multipart/form-data" accept-charset="UTF-8">
					{{ csrf_field() }}

					<div class="form-group">
						<label for="basic-addon1">Name:<span style="color:red;">*</span></label>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('name'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('name') }}</span>
						<input type="text" class="form-control" placeholder="Designation Name" name="name" id="basic-addon1" value="{{ old('name') }}" autofocus required>
					</div>
					<br>
					<div class="form-group">
						<label for="basic-addon2">Description:<span style="color:red;">*</span></label>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('description'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('description') }}</span>
						<textarea class="form-control" placeholder="Designation Description" name="description" id="basic-addon2" value="" rows="3" required></textarea>
					</div>
					<br>
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
				<a href="{{ route('designation.index')}}" style="width: 100px;" class="btn btn-default"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;Back</a>
					<button type="submit" style="width: 100px;" class="btn btn-info pull-right">Submit</button>
				</form>
			</div>
			<!-- /.box-footer -->
		</div>
		<!-- /.box -->
	</div>

<div class="col-md-1"></div>
</div>

@endsection

resources/views/pages/admin/designation/edit.blade.php
@extends('layouts.app')

@section('main-content')
{{-- Error message handle --}}
@if ($message = Session::get('success'))
<div class="container col-md-8">
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
@if ($message = Session::get('error'))
<div class="container">
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
{{-- Validation errors handle --}}
{{-- @if ($errors->first())
<div class="row">
	<div class="container col-md-6 col-sm-6">
		<div class="alert alert-danger" role="alert">
			<p>{{ $errors->first() }}</p>
		</div>
	</div>
</div>
@endif --}}
{{-- End: Error message handle--}}
<div class="container-fluid">
<div class="col-md-1"></div>

	<div class="col-md-10">
		
		<div class="box box-info">
			<div class="box-header with-border">
				{{-- <h3 class="box-title">Update Designation</h3> --}}
				<h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                            UPDATE DESIGNATION
                        </h4>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<form action="{{ route('designation.update', $designationInfo->id) }}" method="POST" role="form" enctype="multipart/form-data" accept-charset="UTF-8">
					{{ csrf_field() }}
					{{ method_field('PATCH') }}

					<div class="form-group">
						<label for="basic-addon1">Name:<span style="color:red;">*</span></label>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('name'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('name') }}</span>
						<input type="text" class="form-control" placeholder="Department Name" name="name" id="basic-addon1" value="{{ $designationInfo->name }}" autofocus required>
					</div>
					<br>
					<div class="form-group">
						<label for="basic-addon2">Description:<span style="color:red;">*</span></label>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('description'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('description') }}</span>
						<textarea class="form-control" placeholder="Department Description" name="description" id="basic-addon2" value="{{ $designationInfo->description }}" rows="3">{{ $designationInfo->description }}</textarea>
					</div>
					<br>
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<a href="{{ route('designation.index')}}" style="width: 100px;" class="btn btn-default"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;Back</a>
					<button type="submit" style="width: 100px;" class="btn btn-info pull-right">Submit</button>
				</form>
			</div>
			<!-- /.box-footer -->
		</div>
		<!-- /.box -->
	</div>

<div class="col-md-1"></div>
</div>

@endsection

resources/views/pages/admin/designation/index.blade.php
@extends('layouts.app')

@section('main-content')
{{-- Error message handle --}}
@if ($message = Session::get('success'))
<div class="container col-md-8">
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
@if ($message = Session::get('error'))
<div class="container">
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
{{-- Validation errors handle --}}
@if ($errors->first())
<div class="row">
	<div class="container col-md-6 col-sm-6">
		<div class="alert alert-danger" role="alert">
			<p>{{ $errors->first() }}</p>
		</div>
	</div>
</div>
@endif
{{-- End: Error message handle--}}
<div class="container-fluid">
<div class="row">
	<div class="col-md-12">
		{{-- <h3>Designation</h3> --}}
		<div class="box box-info">
			<div class="box-header with-border">
				<h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                            DESIGNATION
                        </h4>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
		<div class="pull-right">
			<a class="btn btn-success btn-sm" href="{{ route('designation.create')}}"> Add Designation</a>
		</div>
		<table class="table table-bordered" id="designationTable">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Description</th>
					<th>Created</th>
					<th width="280px">Action</th>
				</tr>
			</thead>
			@php $i=0 @endphp
			@foreach ($designationInfo as $key => $designationInfo)
			<tr>
				<td>{{ $designationInfo->id }}</td>
				<td>{{ $designationInfo->name }}</td>
				<td>{{ $designationInfo->description }}</td>
				<td>{{ date_format($designationInfo->created_at, 'd-m-Y') }}</td>
				<td style="width: 20%">
					{{-- <div class="col-md-2"></div> --}}
					<div class="col-md-6">
						<a class="btn btn-warning btn-block btn-xs" href="{{ route('designation.edit',$designationInfo->id) }}">EDIT</a>
					</div>
					<div class="col-md-6">
						<form method="POST" action="{{ route('designation.destroy', $designationInfo->id) }}" accept-charset="UTF-8">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}
							<button type="submit" class="btn btn-danger btn-block btn-xs disabled" data-toggle="confirmation" data-placement="left" data-singleton="true">DELETE</button>
						</form>
					</div>
					{{-- <div class="col-md-2"></div> --}}
				</td>
			</tr>
			@endforeach
		</table>
		</div>
				<!-- /.box-body -->
				<div class="box-footer">
				</div>
			<!-- /.box-footer -->
		</div>
		<!-- /.box -->
	</div>
</div> {{-- row end --}}
</div>
@endsection