routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('reset_password/{token}', ['as' => 'password.reset', function($token)
{
    // implement your reset password route here!
}]);

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::post('/login', 'Auth\LoginController@postLogin');

Route::group(['prefix' => 'admin','middleware' => ['admin']], function () {
Route::get('/home', 'HomeController@index');
Route::get('/logout', 'HomeController@getSignOut');
Route::get('/getMilestones', 'HomeController@getMilestones');
Route::resource('/department', 'Admin\DepartmentController');
Route::resource('/grade', 'Admin\GradeController');
Route::resource('/designation', 'Admin\DesignationController');
Route::resource('/kpi', 'Admin\KpiController');
Route::resource('/kpiuser', 'Admin\KpiUserController');
Route::resource('/announce', 'Admin\AnnouncementController');
Route::resource('/users', 'Admin\UsersController');
Route::resource('/userlink', 'Admin\UserLinkController');
Route::resource('/milestone', 'Admin\MilestoneController');
Route::post('/copy_kpi_milestone', 'Admin\MilestoneController@copy_kpi_milestone');
Route::resource('/request_meeting', 'Admin\RequestMeetingController');
Route::resource('/notes', 'Admin\NotesController');
Route::get('/milestone/kpibyuser/{id}', 'Admin\MilestoneController@kpibyuser');
});



Route::group(['prefix' => 'user','middleware' => ['user']], function () {
Route::get('/home', 'User\HomeController@index');
Route::get('/my_overall', 'User\MyOverallController@index');
Route::get('/logout', 'User\HomeController@getSignOut');
Route::get('/getMilestones', 'User\HomeController@getMilestones');

Route::get('/kpi/create/{id}', 'User\KpiUsersController@kpiCreate');
Route::post('/kpi/store/', 'User\KpiUsersController@kpiStore');
Route::get('/milestone/create', 'User\KpiUsersController@milestoneCreate');
Route::get('/milestone/kpibyuser/{id}', 'User\KpiUsersController@kpibyuser');
Route::post('/milestone/store', 'User\KpiUsersController@milestoneStore');
Route::get('/meeting-request/{id}', 'User\MeetingRequestingController@index');//Ajax call
Route::get('/meeting-request/show/{id}', 'User\MeetingRequestingController@showAll');
Route::post('/meeting-request/state/{id}', 'User\MeetingRequestingController@updateRequest');
Route::get('/milestone/{id}', 'User\KpiUsersController@showMilestone');

Route::get('/milestone/edit/{id}', 'User\KpiUsersController@editMilestone');
Route::get('/milestone/copy/{id}', 'User\KpiUsersController@copyMilestone');
Route::post('/milestone/update/{id}', 'User\KpiUsersController@milestoneUpdate');
Route::post('/milestone/copyupdate', 'User\KpiUsersController@milestoneCopyUpdate');
Route::post('/milestone/stateupdate/{mid}/{kid}', 'User\KpiUsersController@stateupdate');

Route::get('/super_user/{id}', 'User\KpiUsersController@showSuperusers');
Route::get('/sub_users/{id}', 'User\KpiUsersController@index');
Route::get('/user_kpis/{id}', 'User\KpiUsersController@userKpiList');
Route::get('/admin_kpis/{id}', 'User\KpiUsersController@adminKpiList');
Route::post('/kpi/delete/{id}', 'User\KpiUsersController@deleteKpi');
Route::get('/milestone/delete/{id}', 'User\KpiUsersController@deleteMilestone');
Route::get('/announcement/{id}', 'User\AnnouncementController@index');
});

///Crons
Route::get('/m_deadline_inform', 'CronController@m_deadline_inform');

resources/views/pages/admin/announce/create.blade.php
@extends('layouts.app')

@section('main-content')
{{-- Error message handle --}}
@if ($message = Session::get('success'))
<div class="container col-md-8">
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
@if ($message = Session::get('error'))
<div class="container">
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
{{-- Validation errors handle --}}
{{-- @if ($errors->first())
<div class="row">
	<div class="container col-md-6 col-sm-6">
		<div class="alert alert-danger" role="alert">
			<p>{{ $errors->first() }}</p>
		</div>
	</div>
</div>
@endif --}}
{{-- End: Error message handle--}}
<div class="container-fluid">
<div class="col-md-1"></div>
	<div class="col-md-10">
		<div class="box box-info">
			<div class="box-header with-border">
				{{-- <h3 class="box-title">Create Announcement</h3> --}}
				<h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                            CREATE ANNOUNCEMENT
                        </h4>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<form action="{{ route('announce.store') }}" method="POST" role="form" enctype="multipart/form-data" accept-charset="UTF-8">
					{{ csrf_field() }}

					<div class="form-group">
						<label for="basic-addon1">Title:<span style="color:red;">*</span></label>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('title'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('title') }}</span>
						<input type="text" class="form-control" placeholder="Announcement Title" name="title" id="basic-addon1" value="{{ old('title') }}" autofocus required>
					</div>
					<br>
					<div class="form-group">
						<label for="basic-addon2">Description:<span style="color:red;">*</span></label>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('description'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('description') }}</span>
						<textarea class="form-control" placeholder="Announcement Description" name="description" id="basic-addon2" value="{{ old('title') }}" rows="3" required></textarea>
					</div>
					<div class="form-inline">
					<div class="form-group">
						<label for="date-basic-addon13">Start Date:<span style="color:red;">*</span></label>
						<input type="text" class="form-control date-basic-addon13" placeholder="Announce appear from" name="start_date" id="date-basic-addon13" value="" autofocus>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('start_date'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('start_date.*') }}</span>
					</div>
					<div class="form-group">
						<label for="date-basic-addon14">&nbsp;&nbsp;End Date:<span style="color:red;">*</span></label>
						<input type="text" class="form-control date-basic-addon14" placeholder="Announce appear expire" name="end_date" id="date-basic-addon14" value="" autofocus>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('end_date'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('end_date.*') }}</span>
					</div>
					</div>
					<br>
					<div class="form-group">
						<label id="basic-addon2">Announcement Type:<span style="color:red;">*</span>&nbsp;&nbsp;</label>
						<label class="radio-inline" for="basic-addon2">
							<input type="radio" id="basic-addon2" name="user_type" value="0" onclick="hide();" >Public
						</label>
						<label class="radio-inline" for="basic-addon2">
							<input type="radio" id="basic-addon2" name="user_type" value="1" onclick="show();">Private
						</label>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('user_type'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('user_type') }}</span>
					</div>
					<br>
					<div class="input-group" style="visibility: hidden" id="privateUsers">
						<span class="input-group-addon" id="basic-addon3">Users: </span>
						<select data-placeholder="Choose a Users" class="chosen-select" multiple tabindex="4" style="width: 300px" name="user_id[]" aria-describedby="basic-addon3">
							<option value=""></option>
							@foreach($userList as $row)
							<option value="{{$row->id}}">{{$row->name }}</option>
							@endforeach 
						</select>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('user_id[]'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('user_id[]') }}</span>
					</div>
					
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
				<a href="{{ route('announce.index')}}" style="width: 100px;" class="btn btn-default"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;Back</a>
					<button type="submit" style="width: 100px;" class="btn btn-info pull-right">Submit</button>
				</form>
			</div>
			<!-- /.box-footer -->
		</div>
		<!-- /.box -->
	</div>

<div class="col-md-1"></div>
</div>

{{-- =====Java script for select private users==== --}}
<script type="text/javascript">
	function show() { document.getElementById('privateUsers').style.visibility = 'visible'; }
	function hide() { document.getElementById('privateUsers').style.visibility = 'hidden'; }
</script>
{{-- ===end=== --}}
@endsection

resources/views/pages/admin/announce/edit.blade.php
@extends('layouts.app')

@section('main-content')
{{-- Error message handle --}}
@if ($message = Session::get('success'))
<div class="container col-md-8">
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
@if ($message = Session::get('error'))
<div class="container">
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
    {{-- Validation errors handle --}}
{{--     @if ($errors->first())
    <div class="row">
        <div class="container col-md-6 col-sm-6">
            <div class="alert alert-danger" role="alert">
                <p>{{ $errors->first() }}</p>
            </div>
        </div>
    </div>
    @endif --}}
{{-- End: Error message handle--}}
<div class="container-fluid">
<div class="col-md-1"></div>
	<div class="col-md-10">
<div class="box box-info">
	<div class="box-header with-border">
		{{-- <h3 class="box-title">Update Announcements</h3> --}}
		<h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                            UPDATE ANNOUNCEMENT
                        </h4>
	</div>
	<!-- /.box-header -->
	<div class="box-body">
		<form action="{{ route('announce.update', $announceInfo->id) }}" method="POST" role="form" enctype="multipart/form-data" accept-charset="UTF-8">
			{{ csrf_field() }}
			{{ method_field('PATCH') }}

			<div class="form-group">
				<label for="basic-addon1">Title:<span style="color:red;">*</span></label>
				<span style="color: red">&nbsp;&nbsp;@if($errors->first('title'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('title') }}</span>
				<input type="text" class="form-control" placeholder="Announcement Title" name="title" id="basic-addon1" value="{{ $announceInfo->title }}" autofocus required>
			</div>
			<br>
			<div class="form-group">
				<label for="basic-addon2">Description:<span style="color:red;">*</span></label>
				<span style="color: red">&nbsp;&nbsp;@if($errors->first('description'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('description') }}</span>
				<textarea class="form-control" placeholder="Announcement Description" name="description" id="basic-addon2" rows="3" required>{{ $announceInfo->description }}</textarea>
			</div>
			<div class="form-inline">
					<div class="form-group">
						<label for="date-basic-addon13">Start Date:<span style="color:red;">*</span></label>
						<input type="text" class="form-control date-basic-addon13" placeholder="Announce appear from" name="start_date" id="date-basic-addon13" value="{{$announceInfo->start_date}}" autofocus>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('start_date'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('start_date') }}</span>
					</div>
					<div class="form-group">
						<label for="date-basic-addon14">&nbsp;&nbsp;End Date:<span style="color:red;">*</span></label>
						<input type="text" class="form-control date-basic-addon14" placeholder="Announce appear expire" name="end_date" id="date-basic-addon14" value="{{$announceInfo->end_date}}" autofocus>
						<span style="color: red">&nbsp;&nbsp;@if($errors->first('end_date'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('end_date') }}</span>
					</div>
					</div>
			<br>
			<div class="form-group">
				<label for="basic-addon2">Announcement Type:&nbsp;&nbsp;</label>
				<label class="radio-inline" for="basic-addon2">
				<input type="radio" id="public" name="user_type" value="0" onclick="hide();"
				@if($announceInfo->user_type == '0')
						checked 
				@endif
				>Public
				</label>
				<label class="radio-inline" for="basic-addon2">
					<input type="radio" id="private" name="user_type" value="1" onclick="show();"
					@if($announceInfo->user_type == '1')
						checked 
					@endif
					>Private
				</label>
				<span style="color: red">&nbsp;&nbsp;@if($errors->first('user_type'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('user_type') }}</span>
			</div>
			<br>
			<div class="input-group" 
			@if($announceInfo->user_type == '1')
			style="visibility: visible"
			@elseif($announceInfo->user_type == '0')
			style="visibility: hidden"
			@endif
			id="privateUsers">
				<span class="input-group-addon" id="basic-addon3">Users: </span>
				 <select data-placeholder="Choose a Users" class="chosen-select" multiple tabindex="4" style="width: 300px" name="user_id[]" aria-describedby="basic-addon3">
					<option value=""></option>
					@foreach($userList as $row)
					<option value="{{$row->id}}"
					@if(in_array($row->id, $announceUserInfo))
						selected 
					@endif
					>{{$row->name }}</option>
					@endforeach 
				</select>
				<span style="color: red">&nbsp;&nbsp;@if($errors->first('user_id[]'))<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>@endif{{ $errors->first('user_id[]') }}</span>
			</div>
			<br>
			</div>
	<!-- /.box-body -->
	<div class="box-footer">
		<a href="{{ route('announce.index')}}" style="width: 100px;" class="btn btn-default"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;Back</a>
			<button type="submit" style="width: 100px;" class="btn btn-info pull-right">Submit</button>
		</form>
	</div>
	<!-- /.box-footer -->
	</div>
<!-- /.box -->
	</div>

<div class="col-md-1"></div>
</div>
{{-- =====Java script for select private users==== --}}
<script type="text/javascript">
        function show() { document.getElementById('privateUsers').style.visibility = 'visible'; }
        function hide() { document.getElementById('privateUsers').style.visibility = 'hidden'; }
      </script>
{{-- ===end=== --}}
@endsection

resources/views/pages/admin/announce/index.blade.php
@extends('layouts.app')

@section('main-content')
{{-- Error message handle --}}
@if ($message = Session::get('success'))
<div class="container col-md-8">
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
@if ($message = Session::get('error'))
<div class="container">
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p>{{ $message }}</p>
	</div>
</div>
@endif
{{-- Validation errors handle --}}
@if ($errors->first())
<div class="row">
	<div class="container col-md-6 col-sm-6">
		<div class="alert alert-danger" role="alert">
			<p>{{ $errors->first() }}</p>
		</div>
	</div>
</div>
@endif
{{-- End: Error message handle--}}
<div class="container-fluid">
<div class="row">
	<div class="col-md-12">
		{{-- <h3>Announcements</h3> --}}
		<div class="box box-info">
			<div class="box-header with-border">
				<h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                            ANNOUNCEMENTS
                        </h4>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
		<div class="pull-right">
			<a class="btn btn-success btn-sm" href="{{ route('announce.create')}}"> Add Announcement</a>
		</div>
		<table class="table table-bordered" id="announceTable">
			<thead>
				<tr>
					<th>#</th>
					<th>Title</th>
					<th>Description</th>
					<th>User Type</th>
					<th>Start</th>
					<th>Expire</th>
					<th>Created</th>
					<th width="280px">Action</th>
				</tr>
			</thead>
			@php $i=0 @endphp
			@foreach ($announceInfo as $key => $announceInfo)
			<tr>
				<td>{{ $announceInfo->id }}</td>
				<td>{{ $announceInfo->title }}</td>
				<td>{{ $announceInfo->description }}</td>
				<td>
					@if($announceInfo->user_type == 0) PUBLIC @endif
					@if($announceInfo->user_type == 1) PRIVATE @endif
				</td>
				<td>{{ $announceInfo->start_date }}</td>
				<td>{{ $announceInfo->end_date }}</td>
				<td>{{ date_format($announceInfo->created_at, 'd-m-Y') }}</td>
				<td style="width: 20%">
					{{-- <div class="col-md-2"></div> --}}
					<div class="col-md-6">
						<a class="btn btn-warning btn-block btn-xs" href="{{ route('announce.edit',$announceInfo->id) }}">EDIT</a>
					</div>
					<div class="col-md-6">
						<form method="POST" action="{{ route('announce.destroy', $announceInfo->id) }}" accept-charset="UTF-8">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}
							<button type="submit" class="btn btn-danger btn-block btn-xs" data-toggle="confirmation" data-placement="left" data-singleton="true">DELETE</button>
						</form>
					</div>
					{{-- <div class="col-md-2"></div> --}}
				</td>
			</tr>
			@endforeach
		</table>
		</div>
				<!-- /.box-body -->
				<div class="box-footer">
				</div>
			<!-- /.box-footer -->
		</div>
		<!-- /.box -->
	</div>
</div> {{-- row end --}}
</div>
@endsection